### PR TITLE
ci: secure ci github actions and add security policy 

### PR DESCRIPTION
**Pull request by wallies**
Fixing some of the issues listed here https://github.com/Kapiche/vue-segment-analytics/security/code-scanning that come from the OSSF scorecard

### CODE REVIEW

**Comment by varunsh-coder** [comment]
Hi @wallies, happy to see you use `harden-runner` in your workflow. I hope you don't mind me reaching out. I was curious why you had not turned on the `block` mode. You get a link to insights and a recommended policy in the build log, e.g. https://github.com/Kapiche/vue-segment-analytics/runs/5000075966?check_suite_focus=true#step:4:5. You can then change the mode from `audit` to `block` after setting a list of `allowed-endpoints`...Thanks!

**Comment by wallies** [comment]
Thanks @varunsh-coder that is very helpful. Will turn that on today.

**Comment by varunsh-coder** [comment]
Hi @wallies I was looking at the error log for `harden-runner` insights API and observed a failure. Looks like it was from a workflow in the `Kapiche` org. Wanted to inform you that `harden-runner` does not work for `private` repositories as of now. Please let me know if you would like to pilot that? Please see the discussion [here](https://github.com/step-security/harden-runner/discussions/74). Thanks!

**Comment by wallies** [comment]
> 

Would love to trial that @varunsh-coder. Ive added a lot of the insights i pulled from this repository, but we do a lot of other checks on private respositories, so pilot access, would be good. Once you turn block mode on does it send insights out anymore?

**Comment by varunsh-coder** [comment]
> Would love to trial that @varunsh-coder. Ive added a lot of the insights i pulled from this repository, but we do a lot of other checks on private respositories, so pilot access, would be good. 

Great to hear @wallies! The support for private repos is not coded yet. The insights API needs access to the build logs, so you will need to install a GitHub App and grant it `actions: read` access. Will that be ok? 

> Once you turn block mode on does it send insights out anymore?

As of now, yes, but if you would prefer for it to not do that, I can make that configurable. 

Feel free to email me at info@stepsecurity.io if you prefer to discuss the requirements over email...I am fine discussing it here, or if it is ok with you, at the [discussions](https://github.com/step-security/harden-runner/discussions/74) section. That way others can also read and comment on the requirements...Thanks!

**Comment by varunsh-coder** [comment]
Hi @wallies I have setup a [landing page](https://www.stepsecurity.io) for StepSecurity, and am adding testimonials there. Would you like to add one for `harden-runner`? If so, feel free to just add to this comment, and I will add to the website. or if you want you can email me at info@stepsecurity.io. 

Also, please have a look at some of the planned features (under [discussions](https://github.com/step-security/harden-runner/discussions), specially around SLSA levels and SBOM) to see if they seem valuable or suggest others that you feel are missing in the supply chain area. Thanks!

**Pull request merged**
